# Wrap Up

## Survey

Main survey (anonymous):

Server/Certificate survey (super quick):


## Quesions

If you have bioinformatics or technical questions, please email inbre\@ncgr.org, which will send emails to everyone on the inbre team. If you have questions on passwords/password resets, payments, receipts, etc, please email Ethan Price at eprice\@ncgr.org and cc inbre\@ncgr.org. Occasionally, we change servers or change how to log in so if you are having issues, please contact us.


## Server access and aknowledgements

For those of you who requested continued access to our server, we will extend your account for 1 year. If you need it longer, please email us and we'll be happy to work with you. We ask that you don't run really large jobs while we are running workshops to avoid slowing things down. So, if you have a really large job to run, please check in with us so we can let you know when workshops will be happening.

Please note, if you use our servers to do analysis that you publish, you need to acknowledge the National Center for Genome Resources (NCGR) and the INBRE grant in your acknowledgements. Instructions for the latter can be found here:
https://nminbre.nmsu.edu/cite-us/cite-us.html. This is really important for our annual reports so thank you in advance!

## Bookdown document
You can share these with other individuals in your lab or fellow students/colleagues but please let us know who is using it so we can account for them on our annual reports (thank you!) (you can email Ethan: eprice\@ncgr.org and cc inbre\@ncgr.org).

## Zoom recordings
Please do not share the zoom recordings as we don't have permissions from everyone who participated. Feel free to use them for your own use.
You can find links to the zoom recordings at: 

The bookdown and zoom recordings will be available for at least 3 months. Please plan to download what you need if you want access longer.
